development:
  adapter: postgresql
  encoding: unicode
  database: info_maps_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: info_maps_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: info_maps_production
  pool: 5
