# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Country.delete_all

countries = Country.create!([
  { region_id: 1, map_id: 'sam1',  slug: 'argentina',        name: 'Argentina' },
  { region_id: 1, map_id: 'sam2',  slug: 'bolivia',          name: 'Bolivia' },
  { region_id: 1, map_id: 'sam3',  slug: 'brazil',           name: 'Brazil' },
  { region_id: 1, map_id: 'sam4',  slug: 'chile',            name: 'Chile' },
  { region_id: 1, map_id: 'sam5',  slug: 'colombia',         name: 'Colombia' },
  { region_id: 1, map_id: 'sam6',  slug: 'ecuador',          name: 'Ecuador' },
  { region_id: 1, map_id: 'sam7',  slug: 'guyana',           name: 'Guyana' },
  { region_id: 1, map_id: 'sam8',  slug: 'french-guiana',    name: 'Guyane (French Guiana)' },
  { region_id: 1, map_id: 'sam9',  slug: 'paraguay',         name: 'Paraguay' },
  { region_id: 1, map_id: 'sam10', slug: 'peru',             name: 'Peru' },
  { region_id: 1, map_id: 'sam11', slug: 'suriname',         name: 'Suriname' },
  { region_id: 1, map_id: 'sam12', slug: 'uruguay',          name: 'Uruguay' },
  { region_id: 1, map_id: 'sam13', slug: 'venezuela',        name: 'Venezuela' },
  { region_id: 1, map_id: 'sam14', slug: 'falkland-islands', name: 'Falkland Islands' },

  { region_id: 2, map_id: 'eu1', slug: 'albania', name: 'Albania' },
  { region_id: 2, map_id: 'eu2', slug: 'andorra', name: 'Andorra' },
  { region_id: 2, map_id: 'eu3', slug: 'austria', name: 'Austria' },
  { region_id: 2, map_id: 'eu4', slug: 'belarus', name: 'Belarus' },
  { region_id: 2, map_id: 'eu5', slug: 'belgium', name: 'Belgium' },
  { region_id: 2, map_id: 'eu6', slug: 'bosnia', name: 'Bosnia and Herzegovina' },
  { region_id: 2, map_id: 'eu7', slug: 'bulgaria', name: 'Bulgaria' },
  { region_id: 2, map_id: 'eu8', slug: 'croatia', name: 'Croatia' },
  { region_id: 2, map_id: 'eu9', slug: 'cyprus', name: 'Cyprus' },
  { region_id: 2, map_id: 'eu10', slug: 'czech', name: 'Czech Republic' },
  { region_id: 2, map_id: 'eu11', slug: 'denmark', name: 'Denmark' },
  { region_id: 2, map_id: 'eu12', slug: 'estonia', name: 'Estonia' },
  { region_id: 2, map_id: 'eu13', slug: 'france', name: 'France' },
  { region_id: 2, map_id: 'eu14', slug: 'finland', name: 'Finland' },
  { region_id: 2, map_id: 'eu15', slug: 'georgia', name: 'Georgia' },
  { region_id: 2, map_id: 'eu16', slug: 'germany', name: 'Germany' },
  { region_id: 2, map_id: 'eu17', slug: 'greece', name: 'Greece' },
  { region_id: 2, map_id: 'eu18', slug: 'hungary', name: 'Hungary' },
  { region_id: 2, map_id: 'eu19', slug: 'iceland', name: 'Iceland' },
  { region_id: 2, map_id: 'eu20', slug: 'ireland', name: 'Ireland' },
  { region_id: 2, map_id: 'eu21', slug: 'san', name: 'San Marino' },
  { region_id: 2, map_id: 'eu22', slug: 'italy', name: 'Italy' },
  { region_id: 2, map_id: 'eu23', slug: 'kosovo', name: 'Kosovo' },
  { region_id: 2, map_id: 'eu24', slug: 'latvia', name: 'Latvia' },
  { region_id: 2, map_id: 'eu25', slug: 'liechtenstein', name: 'Liechtenstein' },
  { region_id: 2, map_id: 'eu26', slug: 'lithuania', name: 'Lithuania' },
  { region_id: 2, map_id: 'eu27', slug: 'luxembourg', name: 'Luxembourg' },
  { region_id: 2, map_id: 'eu28', slug: 'macedonia', name: 'Macedonia ' },
  { region_id: 2, map_id: 'eu29', slug: 'malta', name: 'Malta' },
  { region_id: 2, map_id: 'eu30', slug: 'moldova', name: 'Moldova' },
  { region_id: 2, map_id: 'eu31', slug: 'monaco', name: 'Monaco' },
  { region_id: 2, map_id: 'eu32', slug: 'montenegro', name: 'Montenegro' },
  { region_id: 2, map_id: 'eu33', slug: 'netherlands', name: 'Netherlands' },
  { region_id: 2, map_id: 'eu34', slug: 'norway', name: 'Norway' },
  { region_id: 2, map_id: 'eu35', slug: 'poland', name: 'Poland' },
  { region_id: 2, map_id: 'eu36', slug: 'portugal', name: 'Portugal' },
  { region_id: 2, map_id: 'eu37', slug: 'romania', name: 'Romania' },
  { region_id: 2, map_id: 'eu38', slug: 'russian', name: 'Russian Federation' },
  { region_id: 2, map_id: 'eu39', slug: 'serbia', name: 'Serbia' },
  { region_id: 2, map_id: 'eu40', slug: 'slovakia', name: 'Slovakia' },
  { region_id: 2, map_id: 'eu41', slug: 'slovenia', name: 'Slovenia' },
  { region_id: 2, map_id: 'eu42', slug: 'spain', name: 'Spain' },
  { region_id: 2, map_id: 'eu43', slug: 'sweden', name: 'Sweden' },
  { region_id: 2, map_id: 'eu44', slug: 'switzerland', name: 'Switzerland' },
  { region_id: 2, map_id: 'eu45', slug: 'turkey', name: 'Turkey' },
  { region_id: 2, map_id: 'eu46', slug: 'ukraine', name: 'Ukraine' },
  { region_id: 2, map_id: 'eu48', slug: 'england', name: 'England' },
  { region_id: 2, map_id: 'eu49', slug: 'isle', name: 'Isle of Man' },
  { region_id: 2, map_id: 'eu50', slug: 'northern', name: 'Northern Ireland' },
  { region_id: 2, map_id: 'eu51', slug: 'scotland', name: 'Scotland' },
  { region_id: 2, map_id: 'eu52', slug: 'wales', name: 'Wales' }
])
