# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Country.delete_all

countries = Country.create!([
  { region_id: 1, map_id: 'sam1',  slug: 'argentina',        name: 'Argentina', capital: 'Buenos Aires', currency: 'Argentine peso' },
  { region_id: 1, map_id: 'sam2',  slug: 'bolivia',          name: 'Bolivia', capital: 'Sucre', currency: 'Bolivian boliviano' },
  { region_id: 1, map_id: 'sam3',  slug: 'brazil',           name: 'Brazil', capital: 'Brasilia', currency: 'Brazilian real' },
  { region_id: 1, map_id: 'sam4',  slug: 'chile',            name: 'Chile', capital: 'Santiago', currency: 'Chilean peso' },
  { region_id: 1, map_id: 'sam5',  slug: 'colombia',         name: 'Colombia', capital: 'Bogota', currency: 'Colombian peso' },
  { region_id: 1, map_id: 'sam6',  slug: 'ecuador',          name: 'Ecuador', capital: 'Quito', currency: 'United States dollar' },
  { region_id: 1, map_id: 'sam7',  slug: 'guyana',           name: 'Guyana', capital: 'Georgetown', currency: 'Guyanese dollar' },
  { region_id: 1, map_id: 'sam8',  slug: 'french-guiana',    name: 'Guyane (French Guiana)', capital: 'Cayenne', currency: 'Euro' },
  { region_id: 1, map_id: 'sam9',  slug: 'paraguay',         name: 'Paraguay', capital: 'Asuncion', currency: 'Paraguayan guarani' },
  { region_id: 1, map_id: 'sam10', slug: 'peru',             name: 'Peru', capital: 'Lima', currency: 'Peruvian nuevo sol' },
  { region_id: 1, map_id: 'sam11', slug: 'suriname',         name: 'Suriname', capital: 'Paramaribo' , currency: 'Surinamese dollar' },
  { region_id: 1, map_id: 'sam12', slug: 'uruguay',          name: 'Uruguay', capital: 'Montevideo', currency: 'Uruguayan peso' },
  { region_id: 1, map_id: 'sam13', slug: 'venezuela',        name: 'Venezuela', capital: 'Caracas', currency: 'Venezuelan bolivar' },
  { region_id: 1, map_id: 'sam14', slug: 'falkland-islands', name: 'Falkland Islands', capital: 'Stanley' , currency: 'Falkland Islands pound' },

  { region_id: 2, map_id: 'eu1', slug: 'albania', name: 'Albania', capital: 'Tirana', currency: 'Albanian lek' },
  { region_id: 2, map_id: 'eu2', slug: 'andorra', name: 'Andorra', capital: 'Andorra la Vella', currency: 'Euro' },
  { region_id: 2, map_id: 'eu3', slug: 'austria', name: 'Austria', capital: 'Vienna', currency: 'Euro' },
  { region_id: 2, map_id: 'eu4', slug: 'belarus', name: 'Belarus', capital: 'Minsk', currency: 'Belarusian ruble' },
  { region_id: 2, map_id: 'eu5', slug: 'belgium', name: 'Belgium', capital: 'Brussels', currency: 'Euro' },
  { region_id: 2, map_id: 'eu6', slug: 'bosnia', name: 'Bosnia and Herzegovina', capital: 'Sarajevo', currency: 'Bosnia and Herzegovina convertible mark' },
  { region_id: 2, map_id: 'eu7', slug: 'bulgaria', name: 'Bulgaria', capital: 'Sofia', currency: 'Bulgarian lev' },
  { region_id: 2, map_id: 'eu8', slug: 'croatia', name: 'Croatia', capital: 'Zagreb', currency: 'Croatian kuna' },
  { region_id: 2, map_id: 'eu9', slug: 'cyprus', name: 'Cyprus', capital: 'Nicosia', currency: 'Euro' },
  { region_id: 2, map_id: 'eu10', slug: 'czech', name: 'Czech Republic', capital: 'Prague', currency: 'Czech koruna' },
  { region_id: 2, map_id: 'eu11', slug: 'denmark', name: 'Denmark', capital: 'Copenhagen', currency: 'Danish krone' },
  { region_id: 2, map_id: 'eu12', slug: 'estonia', name: 'Estonia', capital: 'Tallinn', currency: 'Euro' },
  { region_id: 2, map_id: 'eu13', slug: 'france', name: 'France', capital: 'Paris', currency: 'Euro, CFP franc' },
  { region_id: 2, map_id: 'eu14', slug: 'finland', name: 'Finland', capital: 'Helsinki', currency: 'Euro' },
  { region_id: 2, map_id: 'eu15', slug: 'georgia', name: 'Georgia', capital: 'Tbilisi', currency: 'Georgian lari' },
  { region_id: 2, map_id: 'eu16', slug: 'germany', name: 'Germany', capital: 'Berlin', currency: 'Euro' },
  { region_id: 2, map_id: 'eu17', slug: 'greece', name: 'Greece', capital: 'Athens', currency: 'Euro' },
  { region_id: 2, map_id: 'eu18', slug: 'hungary', name: 'Hungary', capital: 'Budapest', currency: 'Hungarian forint' },
  { region_id: 2, map_id: 'eu19', slug: 'iceland', name: 'Iceland', capital: 'Reykjavik', currency: 'Icelandic krona' },
  { region_id: 2, map_id: 'eu20', slug: 'ireland', name: 'Ireland', capital: 'Dublin', currency: 'Euro' },
  { region_id: 2, map_id: 'eu21', slug: 'san', name: 'San Marino', capital: 'San Marino', currency: 'Euro' },
  { region_id: 2, map_id: 'eu22', slug: 'italy', name: 'Italy', capital: 'Rome', currency: 'Euro' },
  { region_id: 2, map_id: 'eu23', slug: 'kosovo', name: 'Kosovo', capital: 'Pristina', currency: 'Euro' },
  { region_id: 2, map_id: 'eu24', slug: 'latvia', name: 'Latvia', capital: 'Riga', currency: 'Latvian lats' },
  { region_id: 2, map_id: 'eu25', slug: 'liechtenstein', name: 'Liechtenstein', capital: 'Vaduz', currency: 'Swiss franc' },
  { region_id: 2, map_id: 'eu26', slug: 'lithuania', name: 'Lithuania', capital: 'Vilnius', currency: 'Lithuanian litas' },
  { region_id: 2, map_id: 'eu27', slug: 'luxembourg', name: 'Luxembourg', capital: 'Luxembourg', currency: 'Euro' },
  { region_id: 2, map_id: 'eu28', slug: 'macedonia', name: 'Macedonia ', capital: 'Skopje', currency: 'Macedonian denar' },
  { region_id: 2, map_id: 'eu29', slug: 'malta', name: 'Malta', capital: 'Valletta', currency: 'Euro' },
  { region_id: 2, map_id: 'eu30', slug: 'moldova', name: 'Moldova', capital: 'Chisinau', currency: 'Moldovan leu' },
  { region_id: 2, map_id: 'eu31', slug: 'monaco', name: 'Monaco', capital: 'Monaco', currency: 'Euro' },
  { region_id: 2, map_id: 'eu32', slug: 'montenegro', name: 'Montenegro', capital: 'Podgorica', currency: 'Euro' },
  { region_id: 2, map_id: 'eu33', slug: 'netherlands', name: 'Netherlands', capital: 'Amsterdam', currency: 'Euro' },
  { region_id: 2, map_id: 'eu34', slug: 'norway', name: 'Norway', capital: 'Oslo', currency: 'Norwegian krone' },
  { region_id: 2, map_id: 'eu35', slug: 'poland', name: 'Poland', capital: 'Warsaw', currency: 'Polish zloty' },
  { region_id: 2, map_id: 'eu36', slug: 'portugal', name: 'Portugal', capital: 'Lisbon', currency: 'Euro' },
  { region_id: 2, map_id: 'eu37', slug: 'romania', name: 'Romania', capital: 'Bucharest', currency: 'Romanian leu' },
  { region_id: 2, map_id: 'eu38', slug: 'russian', name: 'Russian Federation', capital: 'Moscow', currency: 'Russian ruble' },
  { region_id: 2, map_id: 'eu39', slug: 'serbia', name: 'Serbia', capital: 'Belgrade', currency: 'Serbian dinar' },
  { region_id: 2, map_id: 'eu40', slug: 'slovakia', name: 'Slovakia', capital: 'Bratislava', currency: 'Euro' },
  { region_id: 2, map_id: 'eu41', slug: 'slovenia', name: 'Slovenia', capital: 'Ljubljana', currency: 'Euro' },
  { region_id: 2, map_id: 'eu42', slug: 'spain', name: 'Spain', capital: 'Madrid', currency: 'Euro' },
  { region_id: 2, map_id: 'eu43', slug: 'sweden', name: 'Sweden', capital: 'Stockholm', currency: 'Swedish krona' },
  { region_id: 2, map_id: 'eu44', slug: 'switzerland', name: 'Switzerland', capital: 'Bern', currency: 'Swiss franc' },
  { region_id: 2, map_id: 'eu45', slug: 'turkey', name: 'Turkey', capital: 'Ankara', currency: 'Turkish lira' },
  { region_id: 2, map_id: 'eu46', slug: 'ukraine', name: 'Ukraine', capital: 'Kiev', currency: 'Ukranian hryvnia' },
  { region_id: 2, map_id: 'eu48', slug: 'england', name: 'England', capital: 'London', currency: 'Pound sterling' },
  { region_id: 2, map_id: 'eu49', slug: 'isle', name: 'Isle of Man', capital: 'Douglas', currency: 'British pound, Manx pound' },
  { region_id: 2, map_id: 'eu50', slug: 'northern', name: 'Northern Ireland', capital: 'Belfast', currency: 'British pound' },
  { region_id: 2, map_id: 'eu51', slug: 'scotland', name: 'Scotland', capital: 'Edinburgh', currency: 'Pound sterling' },
  { region_id: 2, map_id: 'eu52', slug: 'wales', name: 'Wales', capital: 'Cardiff', currency: 'Pound sterling' }
])
